choicedWords = {choices: [
    "Until Dawn", 
    "The Last Of Us",
    "Super Smash Bros",
    "Dark Souls",
    "Overwatch",
    "Gravity Rush",
    "Metroid",
    "Super Mario World",
    "Final Fantasy",
    "The Legend Of Zelda",
    "Mario Kart",
    "Kingdom Hearts",
    "Bloodborne",
    "Mass Effect",
    "inFAMOUS",
    "Goldeneye",
    "Portal",
    "Battlefield",
    "Silent Hill",
    "Heavenly Sword",
    "Mega Man",
    "Pokemon",
    "Borderlands",
    "Grand Theft Auto",
    "Geometry Wars",
    "Titan Souls",
    "Furi",
    "The Binding of Isaac",
    "Trials Fusion",
    "Journey",
    // "Contrast",
    // "The Swapper",
    // "Hyper Light Drifter",
    // "The Witness",
    // "Joust",
    // "Galaga",
    // "Frogger",
    // "Donkey Kong",
    // "Battle Kid",
    // "Ice Climber",
    // "Kid Icarus",
    // "Fire Emblem",
    // "Banjo Kazooie",
    // "Splatoon",
    // "Castlevania",
    // "Mega Man",
    // "Skyrim",
    // "Fallout",
    // "Paper Mario",
    // "Halo"
]};

module.exports = choicedWords;